### ISSUE TITLE
Packing error!

### ISSUE THREAD

**Issue by ayangweb** [arthur-fontaine/stencil-solid-output-target#6]
Packaging will report an error because of the ts type!

Of course it's only an error reported at the packaging level, it's fine to use!

See what you want to do about it, I can contribute code!

<img width="726" alt="image" src="https://github.com/arthur-fontaine/stencil-solid-output-target/assets/75017711/b5d3f524-8e67-438e-96f0-ad8c247c6411">

<img width="782" alt="image" src="https://github.com/arthur-fontaine/stencil-solid-output-target/assets/75017711/ca678f1d-2b4f-4a3e-864a-55377eb93493">

<img width="1082" alt="image" src="https://github.com/arthur-fontaine/stencil-solid-output-target/assets/75017711/3bd8f369-8a63-436c-9a87-dc02dac25cc5">

**Comment by arthur-fontaine** [comment]
I think it is specific to your `tsconfig.json`. Maybe I can change the way the package is built and use a stricter `tsconfig.json` to support all the other Typescript configuration possibilities, but I do not have a lot of time for this project.

Quick solutions would be:
 - add `"**/solid-component-lib"` to the `exclude` property of your `tsconfig.json` (**you** have to make the change)
 - or add `// @ts-nocheck` at the top of all files when copying the lib ([output-solid.ts:112](https://github.com/arthur-fontaine/stencil-solid-output-target/blob/6577c7f9178c856eebc8adc4e81c1bf26a617a3b/src/output-solid.ts#L112)) (**I** have to make the change)

I think the last one is ok. Do you have an opinion or another solution to suggest?

**Comment by ayangweb** [comment]
> I think it is specific to your `tsconfig.json`. Maybe I can change the way the package is built and use a stricter `tsconfig.json` to support all the other Typescript configuration possibilities, but I do not have a lot of time for this project.
> 
> Quick solutions would be:
> 
> * add `"**/solid-component-lib"` to the `exclude` property of your `tsconfig.json` (**you** have to make the change)
> * or add `// @ts-nocheck` at the top of all files when copying the lib ([output-solid.ts:112](https://github.com/arthur-fontaine/stencil-solid-output-target/blob/6577c7f9178c856eebc8adc4e81c1bf26a617a3b/src/output-solid.ts#L112)) (**I** have to make the change)
> 
> I think the last one is ok. Do you have an opinion or another solution to suggest?

I also think the last one is better, I have tried another solution on my side, you can try it?

<img width="673" alt="image" src="https://github.com/arthur-fontaine/stencil-solid-output-target/assets/75017711/a7879c8f-0126-40c5-9edf-a3cdb11d601f">

<img width="698" alt="image" src="https://github.com/arthur-fontaine/stencil-solid-output-target/assets/75017711/887ebfb1-e74e-424b-8c0a-68645597c677">

**Comment by arthur-fontaine** [comment]
> I have tried another solution on my side, you can try it?

I also tried it (in a different way), but I think the `// @ts-nocheck` is better to prevent any unexpected future errors.

**Comment by arthur-fontaine** [comment]
Does installing #10 fix the bug for you?

**Comment by ayangweb** [comment]
> Does installing #10 fix the bug for you?

Yes, it does solve the problem!

**Comment by ayangweb** [comment]
> Does installing #10 fix the bug for you?

No, it still reports an error!

<img width="1738" alt="image" src="https://github.com/arthur-fontaine/stencil-solid-output-target/assets/75017711/9ad1410c-caf1-4d12-af16-f9b8f342c225">

I think you should add `// @ts-nocheck` to this file.

**Comment by arthur-fontaine** [comment]
`@ts-nocheck` is added to all files in the solid-component-lib at the build step (`stencil-solid-output-target` build, not your side).
https://github.com/arthur-fontaine/stencil-solid-output-target/blob/71ca4c19896e67feb62bb6db6c6d95485c3bd9a1/build.config.ts#L13-L30

You can see it in the `dist` directory.
https://github.com/arthur-fontaine/stencil-solid-output-target/blob/71ca4c19896e67feb62bb6db6c6d95485c3bd9a1/dist/solid-component-lib/createComponent.tsx#L1

Did you force reinstall the PR10 version?

**Comment by ayangweb** [comment]
> `@ts-nocheck` is added to all files in the solid-component-lib at the build step (`stencil-solid-output-target` build, not your side).
> 
> https://github.com/arthur-fontaine/stencil-solid-output-target/blob/71ca4c19896e67feb62bb6db6c6d95485c3bd9a1/build.config.ts#L13-L30
> 
> You can see it in the `dist` directory.
> 
> https://github.com/arthur-fontaine/stencil-solid-output-target/blob/71ca4c19896e67feb62bb6db6c6d95485c3bd9a1/dist/solid-component-lib/createComponent.tsx#L1
> 
> Did you force reinstall the PR10 version?

Yes, I meant for you to add it to this file, it doesn't report errors anymore!

**Comment by ayangweb** [comment]
@arthur-fontaine Hey👋, I'm really sorry to bother you, don't forget my help me out when you're free!

**Comment by arthur-fontaine** [comment]
> No, it still reports an error!

> Yes, I meant for you to add it to this file, it doesn't report errors anymore!

Sorry I don't understand, does the PR10 works for you or not?

**Comment by ayangweb** [comment]
> > No, it still reports an error!
> 
> > Yes, I meant for you to add it to this file, it doesn't report errors anymore!
> 
> Sorry I don't understand, does the PR10 works for you or not?

This is fine, it's mainly the `Event` that doesn't work, but it's ok now!

**Comment by arthur-fontaine** [comment]
Okay, I will merge and release asap

**Comment by ayangweb** [comment]
> Okay, I will merge and release asap

Ok, is it possible to consider adding the `style` and `slot` types by the way? #12 #13

**Comment by arthur-fontaine** [comment]
I will take a look. I do not have a lot of time, do not hesitate to make a PR!

**Comment by ayangweb** [comment]
> I will take a look. I do not have a lot of time, do not hesitate to make a PR!

Haha, I'll try it!

**Comment by ayangweb** [comment]
> I will take a look. I do not have a lot of time, do not hesitate to make a PR!

I submitted pr, you can review it for me!
