### ISSUE TITLE
Update `@stencil/core` to latest

### ISSUE THREAD

**Issue by ayangweb** [arthur-fontaine/stencil-solid-output-target#7]
Hi 👋, can you support to the latest version of `stencil`.

<img width="435" alt="image" src="https://github.com/arthur-fontaine/stencil-solid-output-target/assets/75017711/5f45078d-36e3-452a-a300-950f035e2c12">

**Comment by arthur-fontaine** [comment]
@ayangweb can you confirm that there is no more warning by following the step in the PR?

**Comment by ayangweb** [comment]
> @ayangweb can you confirm that there is no more warning by following the step in the PR?

Responded in PR

**Comment by ayangweb** [comment]
@arthur-fontaine Hey👋, if you have time, don't forget to help me solve the issues! Thank you very much!

**Comment by arthur-fontaine** [comment]
Sorry for the delay due to personal issues.

I think I will change the way I version this package to `STENCIL_VERSION.MINOR.PATCH`. Thus, I will release new releases: `3.0.0` (with `"@stencil/core":"^3"`) and `4.0.0` (with `"@stencil/core":"^4"`).
The version for Stencil 2 will still be the current version (`0.1.2`).

**Comment by ayangweb** [comment]
> Sorry for the delay due to personal issues.
> 
> I think I will change the way I version this package to `STENCIL_VERSION.MINOR.PATCH`. Thus, I will release new releases: `3.0.0` (with `"@stencil/core":"^3"`) and `4.0.0` (with `"@stencil/core":"^4"`). The version for Stencil 2 will still be the current version (`0.1.2`).

It's okay. Just fix it when you have time!

I think so, [stencil-hooks](https://github.com/saasquatch/stencil-hooks/pulls?q=is%3Apr+is%3Aclosed) is the way to do it, you can refer to it!

**Comment by arthur-fontaine** [comment]
Fixed by https://github.com/arthur-fontaine/stencil-solid-output-target/pull/9#issuecomment-1694691310
