### ISSUE TITLE
Bug with `@Event`

### ISSUE THREAD

**Issue by arthur-fontaine** [arthur-fontaine/stencil-solid-output-target#8]
As @ayangweb mentionned:

There's a bug where `@Event` defines an event that doesn't work when used! It does work when I use it in `react`! So this should be a problem with solid packaging!

```jsx
@Event() myChange: EventEmitter
```
```jsx
 <MyComponent @eco-change="handleChange" />
```

**Comment by arthur-fontaine** [comment]
@ayangweb Could you provide a repo with a reproducible example please?

**Comment by ayangweb** [comment]
> @ayangweb Could you provide a repo with a reproducible example please?

No problem. Take a look at the program. [https://github.com/ayangweb/stencil-test](https://github.com/ayangweb/stencil-test)

**Comment by arthur-fontaine** [comment]
I have tested the new version with your example and it works.

https://github.com/arthur-fontaine/stencil-solid-output-target/assets/57626613/a2fcd0b5-75b7-4ebd-8042-01985838ac0f

However, I am not a Solid expert. Normally, an event should not be registered twice, but I am not sure about how it will handle if there is a rerender or if the event value passed in prop changes. Can you please test it and make sure it works correctly?
https://github.com/arthur-fontaine/stencil-solid-output-target/blob/29973e8c082b086e9dc74c3223a772abf8e3c972/src/solid-component-lib/createComponent.tsx#L113-L116

**Comment by ayangweb** [comment]
But after my testing, it really doesn't work!

![iShot_2023-08-06_09 45 09](https://github.com/arthur-fontaine/stencil-solid-output-target/assets/75017711/085670c7-736f-4763-87b9-469e4ea1bed3)

**Comment by arthur-fontaine** [comment]
I had to remove the node_modules **and** the pnpm-lock.yaml to correctly update `stencil-solid-output-target` to the PR11 (considering that the version is already changed in the package.json).

```
rm -rf node_modules pnpm-lock.yaml && pnpm i --force
```

**Comment by ayangweb** [comment]
> 

Unfortunately, I tested it and it still doesn't work!

<img width="928" alt="image" src="https://github.com/arthur-fontaine/stencil-solid-output-target/assets/75017711/ef2316d7-84e6-4df5-b1b5-c39e71a3ac70">

**Comment by arthur-fontaine** [comment]
> Unfortunately, I tested it and it still doesn't work!

It looks good to me though... Can you give me more details?

https://github.com/arthur-fontaine/stencil-solid-output-target/assets/57626613/112c53e1-1c33-4896-a988-c13a56189240

1. It does not work with PR10 (as expected)
2. Change to PR11 in the package.json
3. Force install
4. Try to build (does not work as expected, so I edit the lib manually)
5. Build
6. Test and it works

**Comment by ayangweb** [comment]
> > Unfortunately, I tested it and it still doesn't work!
> 
> It looks good to me though... Can you give me more details?
> 
>  Enregistrement.de.l.ecran.2023-08-20.a.03.52.15.mov 
> 1. It does not work with PR10 (as expected)
> 2. Change to PR11 in the package.json
> 3. Force install
> 4. Try to build (does not work as expected, so I edit the lib manually)
> 5. Build
> 6. Test and it works

I'm sorry, you're right, I didn't add `// @ts-nocheck` to my `build` and that's why it didn't work, I added it and rebuilt, and it did work!
